package:
  name: kaldi_native_io
  version: "1.12"

source:
  path: "{{ environ.get('KALDI_NATIVE_IO_ROOT_DIR') }}"

build:
  number: 0
  string: py{{ environ.get('KALDI_NATIVE_IO_PYTHON_VERSION') }}

requirements:
  host:
    - cmake=3.18
    - python
    - gcc_linux-64=7
  run:
    - python

about:
  home: https://github.com/csukuangfj/kaldi_native_io
  license: Apache V2
  license_file: LICENSE
  summary: Python wrapper for kaldi's native I/O
  description: |
    Python wrapper for kaldi's native I/O
