name: build

on:
  push:
    branches:
      - master
      - nightly
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false

    steps:
      - uses: actions/checkout@v2

      # see https://github.com/microsoft/setup-msbuild
      - name: Add msbuild to PATH
        if: startsWith(matrix.os, 'windows')
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - name: Install Python dependencies
        shell: bash
        run: |
          python -m pip install --upgrade numpy

      - name: Configure Cmake
        shell: bash
        run: |
          mkdir build
          cd build
          cmake -D KALDI_NATIVE_IO_BUILD_TESTS=ON -D CMAKE_BUILD_TYPE=Release ..

      - name: Build kaldi_native_io for ubuntu/macos
        if: startsWith(matrix.os, 'ubuntu') || startsWith(matrix.os, 'macos')
        run: |
          cd build
          make -j

      - name: Build kaldi_native_io for windows
        if: startsWith(matrix.os, 'windows')
        run: |
          cd build
          cmake --build . --target ALL_BUILD --config Release

      - name: Test
        if: startsWith(matrix.os, 'ubuntu') || startsWith(matrix.os, 'macos')
        shell: bash
        run: |
          cd build
          ctest --output-on-failure

      - name: Test
        if: startsWith(matrix.os, 'windows')
        shell: bash
        run: |
          cd build
          ctest -C Release --output-on-failure -E py
