name: build-pip

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-pip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - name: Build
        shell: bash
        run: |
          python3 -m pip install -U pip wheel numpy
          python3 setup.py bdist_wheel
          ls -lh dist
          python3 -m pip install ./dist/kaldi*.whl
          cd ../..
          python3 -c "import kaldi_native_io; print(kaldi_native_io.__version__)"
          python3 -c "import kaldi_native_io; print(kaldi_native_io.__file__)"
