name: build-pip

on:
  push:
    branches:
      - master
      - fix-pip
  pull_request:
    branches:
      - master

jobs:
  build-pip:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ["3.6", "3.7", "3.8", "3.9", "3.10"]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-vesion }}

      - name: Python setup.py install
        shell: bash
        run: |
          pip list
          sudo python3 setup.py install
          pip list
          python3 -c "import kaldi_native_io; print(kaldi_native_io.__version__)"
          python3 -c "import kaldi_native_io; print(kaldi_native_io.__file__)"
          sudo python3 -m pip uninstall -y kaldi-native-io
          pip list
          sudo rm -rfv build

      - name: Install from wheel
        shell: bash
        run: |
          ls -lh

          python3 -m pip install -U pip wheel numpy
          python3 setup.py bdist_wheel
          ls -lh dist
          sudo python3 -m pip install ./dist/kaldi*.whl
          cd ../..
          python3 -c "import kaldi_native_io; print(kaldi_native_io.__version__)"
          python3 -c "import kaldi_native_io; print(kaldi_native_io.__file__)"
          pip list
          sudo python3 -m pip uninstall -y kaldi_native_io
          pip list

