name: build-pip

on:
  push:
    branches:
      - master
      - nightly
  pull_request:
    branches:
      - master

jobs:
  build-pip:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, "macos-10.15", windows-latest]
        python-version: ["3.6", "3.7", "3.8", "3.9", "3.10"]
      fail-fast: false
    steps:
      - uses: actions/checkout@v2

      # see https://github.com/microsoft/setup-msbuild
      - name: Add msbuild to PATH
        if: startsWith(matrix.os, 'windows')
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Display Python version
        shell: bash -l {0}
        run: |
          # Note: Don't use python3, use python instead
          python --version
          which python

      - name: Build
        shell: bash
        run: |
          python -m pip install -U pip wheel numpy
          python setup.py bdist_wheel
          ls -lh dist
          python -m pip install ./dist/kaldi*.whl
          cd ../..
          python -c "import kaldi_native_io; print(kaldi_native_io.__version__)"
          python -c "import kaldi_native_io; print(kaldi_native_io.__file__)"
