name: build

on:
  push:
    branches:
      - master
      - fix-pip
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ["3.6", "3.7", "3.8", "3.9", "3.10"]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Python dependencies
        shell: bash
        run: |
          python3 -m pip install --upgrade numpy

      - name: Build
        shell: bash
        run: |
          mkdir build
          cd build
          cmake -D KALDI_NATIVE_IO_BUILD_TESTS=ON ..
          make -j2 VERBOSE=1

          ls -lh lib

      - name: Test
        shell: bash
        run: |
          cd build

          ctest --verbose --output-on-failure
