
name: nightly-pip

on:
  push:
    branches:
      - nightly
  schedule:
    # minute (0-59)
    # hour (0-23)
    # day of the month (1-31)
    # month (1-12)
    # day of the week (0-6)
    # nightly build at 23:50 UTC time every day
    - cron: "50 23 * * *"

jobs:
  nightly-pip:
    # see https://github.com/actions/virtual-environments/blob/win19/20210525.0/images/win/Windows2019-Readme.md
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2019, ubuntu-latest, macos-latest]
        python-version: ["3.6", "3.7", "3.8", "3.9", "3.10"]

    steps:
      # see https://github.com/microsoft/setup-msbuild
      - name: Add msbuild to PATH
        if: startsWith(matrix.os, 'windows')
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Display Python version
        shell: bash -l {0}
        run: |
          python3 -c "import sys; print(sys.version)"
          which python3

      - name: Install kaldi_native_io
        shell: bash -l {0}
        run: |
          python3 -m pip install -U pip wheel numpy

          python3 -m pip install kaldi_native_io

      - name: Display kaldi_native_io version
        shell: bash
        run: |
          python3 -c "import kaldi_native_io; print(kaldi_native_io.__version__)"
          python3 -c "import kaldi_native_io; print(kaldi_native_io.__file__)"
